export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const SAVE_PRODUCT_SUCCESS = "SAVE_PRODUCT_SUCCESS";

export const DEFAULT_CATEGORIES_SUCCESS = "DEFAULT_CATEGORIES_SUCCESS";
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
export const SAVE_CATEGORY_SUCCESS = "SAVE_CATEGORY_SUCCESS";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const REQUEST_LOAD_CATEGORIES = "REQUEST_LOAD_CATEGORIES";
export const REQUEST_LOAD_CATEGORIES_SUCCESS =
  "REQUEST_LOAD_CATEGORIES_SUCCESS";
export const REQUEST_LOAD_PRODUCTS = "REQUEST_LOAD_PRODUCTS";
export const REQUEST_LOAD_PRODUCTS_SUCCESS = "REQUEST_LOAD_PRODUCTS_SUCCESS";

export const LOAD_SHOPCATEGORIES_SUCCESS = "LOAD_SHOPCATEGORIES_SUCCESS";
export const LOAD_BRANDS_SUCCESS = "LOAD_BRANDS_SUCCESS";
export const LOAD_SHOPITEMSBYCATEGORY_SUCCESS =
  "LOAD_SHOPITEMSBYCATEGORY_SUCCESS";
export const SAVE_SHOPCATEGORY_SUCCESS = "SAVE_SHOPCATEGORY_SUCCESS";
export const REQUEST_LOAD_SHOPCATEGORIES = "REQUEST_LOAD_SHOPCATEGORIES";
export const REQUEST_LOAD_SHOPITEMSBYCATEGORY =
  "REQUEST_LOAD_SHOPITEMSBYCATEGORY";
export const REQUEST_LOAD_SHOPCATEGORIES_SUCCESS =
  "REQUEST_LOAD_SHOPCATEGORIES_SUCCESS";
export const REQUEST_LOAD_SHOPITEMSBYCATEGORY_SUCCESS =
  "REQUEST_LOAD_SHOPITEMSBYCATEGORY_SUCCESS";

export const SAVE_SHOPITEM_SUCCESS = "SAVE_SHOPITEM_SUCCESS";
export const LOAD_SHOPITEMSBYCATEGORY = "LOAD_SHOPITEMSBYCATEGORY";
export const LOAD_SHOPITEMSINCREASEPAGENUMBER =
  "LOAD_SHOPITEMSINCREASEPAGENUMBER";

export const LOAD_SHOPITEM_SUCCESS = "LOAD_SHOPITEM_SUCCESS";
export const ADD_SHOPITEMFEEDBACK_SUCCESS = "ADD_SHOPITEMFEEDBACK_SUCCESS";
export const ADD_SHOPITEMFEEDBACK = "ADD_SHOPITEMFEEDBACK";
export const LOAD_SHOPITEMFEEDBACKS_SUCCESS = "LOAD_SHOPITEMFEEDBACKS_SUCCESS";

export const UPDATE_CARTITEMQUANTITY = "UPDATE_CARTITEMQUANTITY";
export const ADD_ITEMINCART = "ADD_ITEMINCART";
export const EMPTY = "EMPTY";
export const UPDATE_SHOPITEM = "UPDATE_SHOPITEM";
export const ADD = "ADD";

export const LOAD_KNOWLEDGECATEGORIES_SUCCESS =
  "LOAD_KNOWLEDGECATEGORIES_SUCCESS";
export const REQUEST_LOAD_KNOWLEDGECATEGORIES_SUCCESS =
  "REQUEST_LOAD_KNOWLEDGECATEGORIES_SUCCESS";
export const SAVE_KNOWLEDGECATEGORY_SUCCESS = "SAVE_KNOWLEDGECATEGORY_SUCCESS";

export const LOAD_ARTICLESBYCATEGORY_SUCCESS =
  "LOAD_ARTICLESBYCATEGORY_SUCCESS";
export const REQUEST_LOAD_ARTICLESBYCATEGORY_SUCCESS =
  "REQUEST_LOAD_ARTICLESBYCATEGORY_SUCCESS";
