export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const SAVE_PRODUCT_SUCCESS = "SAVE_PRODUCT_SUCCESS";

export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
export const SAVE_CATEGORY_SUCCESS = "SAVE_CATEGORY_SUCCESS";
